version: 2

before:
  hooks:
    - go mod download

builds:
  - id: "binary"
    main: ./cmd/arch-lint
    binary: go-arch-lint
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ldflags:
      - -s -w
      - -X 'github.com/vsfedorenko/go-arch-lint/internal/app.Version={{.Version}}'
      - -X 'github.com/vsfedorenko/go-arch-lint/internal/app.CommitHash={{.Commit}}'
      - -X 'github.com/vsfedorenko/go-arch-lint/internal/app.BuildTime={{.Date}}'

archives:
  - format_overrides:
      - goos: windows
        formats: [zip]

dockers:
  - ids:
      - binary
    image_templates:
      - "ghcr.io/vsfedorenko/{{.ProjectName}}:{{.Version}}"
      - "ghcr.io/vsfedorenko/{{.ProjectName}}:{{.Major}}.{{.Minor}}"
      - "ghcr.io/vsfedorenko/{{.ProjectName}}:{{.Major}}"
      - "ghcr.io/vsfedorenko/{{.ProjectName}}:latest"
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
