packages:
  github.com/vsfedorenko/go-arch-lint/v3/internal/app/container:
    interfaces:
      SpecDecoder:
  github.com/vsfedorenko/go-arch-lint/v3/internal/services/checker:
    interfaces:
      SuppressIndex:
  github.com/vsfedorenko/go-arch-lint/v3/internal/services/spec/assembler:
    config:
      all: true
  github.com/vsfedorenko/go-arch-lint/v3/internal/operations/check:
    config:
      all: true
  github.com/vsfedorenko/go-arch-lint/v3/internal/operations/explain:
    config:
      all: true
  github.com/vsfedorenko/go-arch-lint/v3/internal/operations/mapping:
    config:
      all: true
  github.com/vsfedorenko/go-arch-lint/v3/internal/operations/selfInspect:
    config:
      all: true
  github.com/vsfedorenko/go-arch-lint/v3/internal/services/project/resolver:
    config:
      all: true
