// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package assembler

import (
	mock "github.com/stretchr/testify/mock"
	"github.com/vsfedorenko/go-arch-lint/v3/internal/models/arch"
	"github.com/vsfedorenko/go-arch-lint/v3/internal/services/spec"
)

// newMockassembler creates a new instance of mockassembler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockassembler(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockassembler {
	mock := &mockassembler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockassembler is an autogenerated mock type for the assembler type
type mockassembler struct {
	mock.Mock
}

type mockassembler_Expecter struct {
	mock *mock.Mock
}

func (_m *mockassembler) EXPECT() *mockassembler_Expecter {
	return &mockassembler_Expecter{mock: &_m.Mock}
}

// assemble provides a mock function for the type mockassembler
func (_mock *mockassembler) assemble(spec1 *arch.Spec, doc spec.Document) error {
	ret := _mock.Called(spec1, doc)

	if len(ret) == 0 {
		panic("no return value specified for assemble")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*arch.Spec, spec.Document) error); ok {
		r0 = returnFunc(spec1, doc)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockassembler_assemble_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'assemble'
type mockassembler_assemble_Call struct {
	*mock.Call
}

// assemble is a helper method to define mock.On call
//   - spec1 *arch.Spec
//   - doc spec.Document
func (_e *mockassembler_Expecter) assemble(spec1 any, doc any) *mockassembler_assemble_Call {
	return &mockassembler_assemble_Call{Call: _e.mock.On("assemble", spec1, doc)}
}

func (_c *mockassembler_assemble_Call) Run(run func(spec1 *arch.Spec, doc spec.Document)) *mockassembler_assemble_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *arch.Spec
		if args[0] != nil {
			arg0 = args[0].(*arch.Spec)
		}
		var arg1 spec.Document
		if args[1] != nil {
			arg1 = args[1].(spec.Document)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockassembler_assemble_Call) Return(err error) *mockassembler_assemble_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockassembler_assemble_Call) RunAndReturn(run func(spec1 *arch.Spec, doc spec.Document) error) *mockassembler_assemble_Call {
	_c.Call.Return(run)
	return _c
}

// newMockarchDecoder creates a new instance of mockarchDecoder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockarchDecoder(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockarchDecoder {
	mock := &mockarchDecoder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockarchDecoder is an autogenerated mock type for the archDecoder type
type mockarchDecoder struct {
	mock.Mock
}

type mockarchDecoder_Expecter struct {
	mock *mock.Mock
}

func (_m *mockarchDecoder) EXPECT() *mockarchDecoder_Expecter {
	return &mockarchDecoder_Expecter{mock: &_m.Mock}
}

// Decode provides a mock function for the type mockarchDecoder
func (_mock *mockarchDecoder) Decode(archFile string) (spec.Document, []arch.Notice, error) {
	ret := _mock.Called(archFile)

	if len(ret) == 0 {
		panic("no return value specified for Decode")
	}

	var r0 spec.Document
	var r1 []arch.Notice
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(string) (spec.Document, []arch.Notice, error)); ok {
		return returnFunc(archFile)
	}
	if returnFunc, ok := ret.Get(0).(func(string) spec.Document); ok {
		r0 = returnFunc(archFile)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(spec.Document)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) []arch.Notice); ok {
		r1 = returnFunc(archFile)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]arch.Notice)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(string) error); ok {
		r2 = returnFunc(archFile)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// mockarchDecoder_Decode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Decode'
type mockarchDecoder_Decode_Call struct {
	*mock.Call
}

// Decode is a helper method to define mock.On call
//   - archFile string
func (_e *mockarchDecoder_Expecter) Decode(archFile any) *mockarchDecoder_Decode_Call {
	return &mockarchDecoder_Decode_Call{Call: _e.mock.On("Decode", archFile)}
}

func (_c *mockarchDecoder_Decode_Call) Run(run func(archFile string)) *mockarchDecoder_Decode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockarchDecoder_Decode_Call) Return(document spec.Document, notices []arch.Notice, err error) *mockarchDecoder_Decode_Call {
	_c.Call.Return(document, notices, err)
	return _c
}

func (_c *mockarchDecoder_Decode_Call) RunAndReturn(run func(archFile string) (spec.Document, []arch.Notice, error)) *mockarchDecoder_Decode_Call {
	_c.Call.Return(run)
	return _c
}

// newMockarchValidator creates a new instance of mockarchValidator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockarchValidator(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockarchValidator {
	mock := &mockarchValidator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockarchValidator is an autogenerated mock type for the archValidator type
type mockarchValidator struct {
	mock.Mock
}

type mockarchValidator_Expecter struct {
	mock *mock.Mock
}

func (_m *mockarchValidator) EXPECT() *mockarchValidator_Expecter {
	return &mockarchValidator_Expecter{mock: &_m.Mock}
}

// Validate provides a mock function for the type mockarchValidator
func (_mock *mockarchValidator) Validate(doc spec.Document, projectDir string) []arch.Notice {
	ret := _mock.Called(doc, projectDir)

	if len(ret) == 0 {
		panic("no return value specified for Validate")
	}

	var r0 []arch.Notice
	if returnFunc, ok := ret.Get(0).(func(spec.Document, string) []arch.Notice); ok {
		r0 = returnFunc(doc, projectDir)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]arch.Notice)
		}
	}
	return r0
}

// mockarchValidator_Validate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Validate'
type mockarchValidator_Validate_Call struct {
	*mock.Call
}

// Validate is a helper method to define mock.On call
//   - doc spec.Document
//   - projectDir string
func (_e *mockarchValidator_Expecter) Validate(doc any, projectDir any) *mockarchValidator_Validate_Call {
	return &mockarchValidator_Validate_Call{Call: _e.mock.On("Validate", doc, projectDir)}
}

func (_c *mockarchValidator_Validate_Call) Run(run func(doc spec.Document, projectDir string)) *mockarchValidator_Validate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 spec.Document
		if args[0] != nil {
			arg0 = args[0].(spec.Document)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockarchValidator_Validate_Call) Return(notices []arch.Notice) *mockarchValidator_Validate_Call {
	_c.Call.Return(notices)
	return _c
}

func (_c *mockarchValidator_Validate_Call) RunAndReturn(run func(doc spec.Document, projectDir string) []arch.Notice) *mockarchValidator_Validate_Call {
	_c.Call.Return(run)
	return _c
}

// newMockpathResolver creates a new instance of mockpathResolver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockpathResolver(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockpathResolver {
	mock := &mockpathResolver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockpathResolver is an autogenerated mock type for the pathResolver type
type mockpathResolver struct {
	mock.Mock
}

type mockpathResolver_Expecter struct {
	mock *mock.Mock
}

func (_m *mockpathResolver) EXPECT() *mockpathResolver_Expecter {
	return &mockpathResolver_Expecter{mock: &_m.Mock}
}

// Resolve provides a mock function for the type mockpathResolver
func (_mock *mockpathResolver) Resolve(absPath string) ([]string, error) {
	ret := _mock.Called(absPath)

	if len(ret) == 0 {
		panic("no return value specified for Resolve")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]string, error)); ok {
		return returnFunc(absPath)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []string); ok {
		r0 = returnFunc(absPath)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(absPath)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockpathResolver_Resolve_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Resolve'
type mockpathResolver_Resolve_Call struct {
	*mock.Call
}

// Resolve is a helper method to define mock.On call
//   - absPath string
func (_e *mockpathResolver_Expecter) Resolve(absPath any) *mockpathResolver_Resolve_Call {
	return &mockpathResolver_Resolve_Call{Call: _e.mock.On("Resolve", absPath)}
}

func (_c *mockpathResolver_Resolve_Call) Run(run func(absPath string)) *mockpathResolver_Resolve_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockpathResolver_Resolve_Call) Return(resolvePaths []string, err error) *mockpathResolver_Resolve_Call {
	_c.Call.Return(resolvePaths, err)
	return _c
}

func (_c *mockpathResolver_Resolve_Call) RunAndReturn(run func(absPath string) ([]string, error)) *mockpathResolver_Resolve_Call {
	_c.Call.Return(run)
	return _c
}
