// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package container

import (
	mock "github.com/stretchr/testify/mock"
	"github.com/vsfedorenko/go-arch-lint/v2/internal/models/arch"
	"github.com/vsfedorenko/go-arch-lint/v2/internal/services/spec"
)

// NewMockSpecDecoder creates a new instance of MockSpecDecoder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSpecDecoder(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSpecDecoder {
	mock := &MockSpecDecoder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSpecDecoder is an autogenerated mock type for the SpecDecoder type
type MockSpecDecoder struct {
	mock.Mock
}

type MockSpecDecoder_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSpecDecoder) EXPECT() *MockSpecDecoder_Expecter {
	return &MockSpecDecoder_Expecter{mock: &_m.Mock}
}

// Decode provides a mock function for the type MockSpecDecoder
func (_mock *MockSpecDecoder) Decode(archFile string) (spec.Document, []arch.Notice, error) {
	ret := _mock.Called(archFile)

	if len(ret) == 0 {
		panic("no return value specified for Decode")
	}

	var r0 spec.Document
	var r1 []arch.Notice
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(string) (spec.Document, []arch.Notice, error)); ok {
		return returnFunc(archFile)
	}
	if returnFunc, ok := ret.Get(0).(func(string) spec.Document); ok {
		r0 = returnFunc(archFile)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(spec.Document)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) []arch.Notice); ok {
		r1 = returnFunc(archFile)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]arch.Notice)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(string) error); ok {
		r2 = returnFunc(archFile)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockSpecDecoder_Decode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Decode'
type MockSpecDecoder_Decode_Call struct {
	*mock.Call
}

// Decode is a helper method to define mock.On call
//   - archFile string
func (_e *MockSpecDecoder_Expecter) Decode(archFile any) *MockSpecDecoder_Decode_Call {
	return &MockSpecDecoder_Decode_Call{Call: _e.mock.On("Decode", archFile)}
}

func (_c *MockSpecDecoder_Decode_Call) Run(run func(archFile string)) *MockSpecDecoder_Decode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSpecDecoder_Decode_Call) Return(document spec.Document, notices []arch.Notice, err error) *MockSpecDecoder_Decode_Call {
	_c.Call.Return(document, notices, err)
	return _c
}

func (_c *MockSpecDecoder_Decode_Call) RunAndReturn(run func(archFile string) (spec.Document, []arch.Notice, error)) *MockSpecDecoder_Decode_Call {
	_c.Call.Return(run)
	return _c
}
