package main

import (
	"fmt"
	"os"
	"path/filepath"
)

const scaffoldGoMod = `module arch-lint-local

go 1.25

require github.com/fe3dback/go-arch-lint v0.0.0
`

const scaffoldMainGo = `// Code generated by go-arch-lint init. DO NOT EDIT.
package main

import "github.com/fe3dback/go-arch-lint"

func main() {
	archlint.MustRunCLI()
}
`

const scaffoldArchGo = `package main

import . "github.com/fe3dback/go-arch-lint/dsl"

var _ = Spec(func() {
	Version(1)
	Workdir("internal")

	Allow(func() {
		DepOnAnyVendor(false)
	})

	ExcludeFiles(` + "`^.*_test\\.go$`" + `)

	// Define your components:
	// Component("main", "app")
	// Component("services", "services/**")

	// Define dependency rules:
	// Deps("main", func() {
	//     MayDependOn("services")
	// })
})
`

func cmdInit() int {
	projectPath := "."
	archDir := filepath.Join(projectPath, ".go-arch-lint")

	if dirExists(archDir) {
		fmt.Fprintf(os.Stderr, "Error: %s already exists\n", archDir)
		return 1
	}

	if err := os.MkdirAll(archDir, 0755); err != nil {
		fmt.Fprintf(os.Stderr, "Error: failed to create %s: %v\n", archDir, err)
		return 1
	}

	files := map[string]string{
		"go.mod":  scaffoldGoMod,
		"main.go": scaffoldMainGo,
		"arch.go": scaffoldArchGo,
	}

	for name, content := range files {
		path := filepath.Join(archDir, name)
		if err := os.WriteFile(path, []byte(content), 0644); err != nil {
			fmt.Fprintf(os.Stderr, "Error: failed to write %s: %v\n", path, err)
			return 1
		}
		fmt.Printf("  created %s\n", path)
	}

	fmt.Printf("\nNext steps:\n")
	fmt.Printf("  1. Edit %s/arch.go to describe your architecture\n", archDir)
	fmt.Printf("  2. Run 'cd %s && go mod tidy' to resolve dependencies\n", archDir)
	fmt.Printf("  3. Run 'go-arch-lint check' to lint your project\n")

	return 0
}
