// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package resolver

import (
	"context"
	"regexp"

	mock "github.com/stretchr/testify/mock"
	"github.com/vsfedorenko/go-arch-lint/v2/internal/models"
	"github.com/vsfedorenko/go-arch-lint/v2/internal/models/arch"
)

// newMockprojectFilesResolver creates a new instance of mockprojectFilesResolver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockprojectFilesResolver(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockprojectFilesResolver {
	mock := &mockprojectFilesResolver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockprojectFilesResolver is an autogenerated mock type for the projectFilesResolver type
type mockprojectFilesResolver struct {
	mock.Mock
}

type mockprojectFilesResolver_Expecter struct {
	mock *mock.Mock
}

func (_m *mockprojectFilesResolver) EXPECT() *mockprojectFilesResolver_Expecter {
	return &mockprojectFilesResolver_Expecter{mock: &_m.Mock}
}

// Scan provides a mock function for the type mockprojectFilesResolver
func (_mock *mockprojectFilesResolver) Scan(ctx context.Context, projectDirectory string, moduleName string, excludePaths []models.ResolvedPath, excludeFileMatchers []*regexp.Regexp) ([]models.ProjectFile, error) {
	ret := _mock.Called(ctx, projectDirectory, moduleName, excludePaths, excludeFileMatchers)

	if len(ret) == 0 {
		panic("no return value specified for Scan")
	}

	var r0 []models.ProjectFile
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, []models.ResolvedPath, []*regexp.Regexp) ([]models.ProjectFile, error)); ok {
		return returnFunc(ctx, projectDirectory, moduleName, excludePaths, excludeFileMatchers)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, []models.ResolvedPath, []*regexp.Regexp) []models.ProjectFile); ok {
		r0 = returnFunc(ctx, projectDirectory, moduleName, excludePaths, excludeFileMatchers)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.ProjectFile)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, []models.ResolvedPath, []*regexp.Regexp) error); ok {
		r1 = returnFunc(ctx, projectDirectory, moduleName, excludePaths, excludeFileMatchers)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockprojectFilesResolver_Scan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Scan'
type mockprojectFilesResolver_Scan_Call struct {
	*mock.Call
}

// Scan is a helper method to define mock.On call
//   - ctx context.Context
//   - projectDirectory string
//   - moduleName string
//   - excludePaths []models.ResolvedPath
//   - excludeFileMatchers []*regexp.Regexp
func (_e *mockprojectFilesResolver_Expecter) Scan(ctx any, projectDirectory any, moduleName any, excludePaths any, excludeFileMatchers any) *mockprojectFilesResolver_Scan_Call {
	return &mockprojectFilesResolver_Scan_Call{Call: _e.mock.On("Scan", ctx, projectDirectory, moduleName, excludePaths, excludeFileMatchers)}
}

func (_c *mockprojectFilesResolver_Scan_Call) Run(run func(ctx context.Context, projectDirectory string, moduleName string, excludePaths []models.ResolvedPath, excludeFileMatchers []*regexp.Regexp)) *mockprojectFilesResolver_Scan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []models.ResolvedPath
		if args[3] != nil {
			arg3 = args[3].([]models.ResolvedPath)
		}
		var arg4 []*regexp.Regexp
		if args[4] != nil {
			arg4 = args[4].([]*regexp.Regexp)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *mockprojectFilesResolver_Scan_Call) Return(projectFiles []models.ProjectFile, err error) *mockprojectFilesResolver_Scan_Call {
	_c.Call.Return(projectFiles, err)
	return _c
}

func (_c *mockprojectFilesResolver_Scan_Call) RunAndReturn(run func(ctx context.Context, projectDirectory string, moduleName string, excludePaths []models.ResolvedPath, excludeFileMatchers []*regexp.Regexp) ([]models.ProjectFile, error)) *mockprojectFilesResolver_Scan_Call {
	_c.Call.Return(run)
	return _c
}

// newMockprojectFilesHolder creates a new instance of mockprojectFilesHolder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockprojectFilesHolder(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockprojectFilesHolder {
	mock := &mockprojectFilesHolder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockprojectFilesHolder is an autogenerated mock type for the projectFilesHolder type
type mockprojectFilesHolder struct {
	mock.Mock
}

type mockprojectFilesHolder_Expecter struct {
	mock *mock.Mock
}

func (_m *mockprojectFilesHolder) EXPECT() *mockprojectFilesHolder_Expecter {
	return &mockprojectFilesHolder_Expecter{mock: &_m.Mock}
}

// HoldProjectFiles provides a mock function for the type mockprojectFilesHolder
func (_mock *mockprojectFilesHolder) HoldProjectFiles(files []models.ProjectFile, components []arch.Component) []models.FileHold {
	ret := _mock.Called(files, components)

	if len(ret) == 0 {
		panic("no return value specified for HoldProjectFiles")
	}

	var r0 []models.FileHold
	if returnFunc, ok := ret.Get(0).(func([]models.ProjectFile, []arch.Component) []models.FileHold); ok {
		r0 = returnFunc(files, components)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.FileHold)
		}
	}
	return r0
}

// mockprojectFilesHolder_HoldProjectFiles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HoldProjectFiles'
type mockprojectFilesHolder_HoldProjectFiles_Call struct {
	*mock.Call
}

// HoldProjectFiles is a helper method to define mock.On call
//   - files []models.ProjectFile
//   - components []arch.Component
func (_e *mockprojectFilesHolder_Expecter) HoldProjectFiles(files any, components any) *mockprojectFilesHolder_HoldProjectFiles_Call {
	return &mockprojectFilesHolder_HoldProjectFiles_Call{Call: _e.mock.On("HoldProjectFiles", files, components)}
}

func (_c *mockprojectFilesHolder_HoldProjectFiles_Call) Run(run func(files []models.ProjectFile, components []arch.Component)) *mockprojectFilesHolder_HoldProjectFiles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []models.ProjectFile
		if args[0] != nil {
			arg0 = args[0].([]models.ProjectFile)
		}
		var arg1 []arch.Component
		if args[1] != nil {
			arg1 = args[1].([]arch.Component)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockprojectFilesHolder_HoldProjectFiles_Call) Return(fileHolds []models.FileHold) *mockprojectFilesHolder_HoldProjectFiles_Call {
	_c.Call.Return(fileHolds)
	return _c
}

func (_c *mockprojectFilesHolder_HoldProjectFiles_Call) RunAndReturn(run func(files []models.ProjectFile, components []arch.Component) []models.FileHold) *mockprojectFilesHolder_HoldProjectFiles_Call {
	_c.Call.Return(run)
	return _c
}
