// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package check

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/vsfedorenko/go-arch-lint/v2/internal/models"
	"github.com/vsfedorenko/go-arch-lint/v2/internal/models/arch"
	"github.com/vsfedorenko/go-arch-lint/v2/internal/models/domain"
)

// newMockprojectInfoAssembler creates a new instance of mockprojectInfoAssembler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockprojectInfoAssembler(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockprojectInfoAssembler {
	mock := &mockprojectInfoAssembler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockprojectInfoAssembler is an autogenerated mock type for the projectInfoAssembler type
type mockprojectInfoAssembler struct {
	mock.Mock
}

type mockprojectInfoAssembler_Expecter struct {
	mock *mock.Mock
}

func (_m *mockprojectInfoAssembler) EXPECT() *mockprojectInfoAssembler_Expecter {
	return &mockprojectInfoAssembler_Expecter{mock: &_m.Mock}
}

// ProjectInfo provides a mock function for the type mockprojectInfoAssembler
func (_mock *mockprojectInfoAssembler) ProjectInfo(rootDirectory string, archFilePath string) (domain.Project, error) {
	ret := _mock.Called(rootDirectory, archFilePath)

	if len(ret) == 0 {
		panic("no return value specified for ProjectInfo")
	}

	var r0 domain.Project
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) (domain.Project, error)); ok {
		return returnFunc(rootDirectory, archFilePath)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) domain.Project); ok {
		r0 = returnFunc(rootDirectory, archFilePath)
	} else {
		r0 = ret.Get(0).(domain.Project)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(rootDirectory, archFilePath)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockprojectInfoAssembler_ProjectInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProjectInfo'
type mockprojectInfoAssembler_ProjectInfo_Call struct {
	*mock.Call
}

// ProjectInfo is a helper method to define mock.On call
//   - rootDirectory string
//   - archFilePath string
func (_e *mockprojectInfoAssembler_Expecter) ProjectInfo(rootDirectory any, archFilePath any) *mockprojectInfoAssembler_ProjectInfo_Call {
	return &mockprojectInfoAssembler_ProjectInfo_Call{Call: _e.mock.On("ProjectInfo", rootDirectory, archFilePath)}
}

func (_c *mockprojectInfoAssembler_ProjectInfo_Call) Run(run func(rootDirectory string, archFilePath string)) *mockprojectInfoAssembler_ProjectInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockprojectInfoAssembler_ProjectInfo_Call) Return(project domain.Project, err error) *mockprojectInfoAssembler_ProjectInfo_Call {
	_c.Call.Return(project, err)
	return _c
}

func (_c *mockprojectInfoAssembler_ProjectInfo_Call) RunAndReturn(run func(rootDirectory string, archFilePath string) (domain.Project, error)) *mockprojectInfoAssembler_ProjectInfo_Call {
	_c.Call.Return(run)
	return _c
}

// newMockspecAssembler creates a new instance of mockspecAssembler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockspecAssembler(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockspecAssembler {
	mock := &mockspecAssembler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockspecAssembler is an autogenerated mock type for the specAssembler type
type mockspecAssembler struct {
	mock.Mock
}

type mockspecAssembler_Expecter struct {
	mock *mock.Mock
}

func (_m *mockspecAssembler) EXPECT() *mockspecAssembler_Expecter {
	return &mockspecAssembler_Expecter{mock: &_m.Mock}
}

// Assemble provides a mock function for the type mockspecAssembler
func (_mock *mockspecAssembler) Assemble(prj domain.Project) (arch.Spec, error) {
	ret := _mock.Called(prj)

	if len(ret) == 0 {
		panic("no return value specified for Assemble")
	}

	var r0 arch.Spec
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(domain.Project) (arch.Spec, error)); ok {
		return returnFunc(prj)
	}
	if returnFunc, ok := ret.Get(0).(func(domain.Project) arch.Spec); ok {
		r0 = returnFunc(prj)
	} else {
		r0 = ret.Get(0).(arch.Spec)
	}
	if returnFunc, ok := ret.Get(1).(func(domain.Project) error); ok {
		r1 = returnFunc(prj)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockspecAssembler_Assemble_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Assemble'
type mockspecAssembler_Assemble_Call struct {
	*mock.Call
}

// Assemble is a helper method to define mock.On call
//   - prj domain.Project
func (_e *mockspecAssembler_Expecter) Assemble(prj any) *mockspecAssembler_Assemble_Call {
	return &mockspecAssembler_Assemble_Call{Call: _e.mock.On("Assemble", prj)}
}

func (_c *mockspecAssembler_Assemble_Call) Run(run func(prj domain.Project)) *mockspecAssembler_Assemble_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 domain.Project
		if args[0] != nil {
			arg0 = args[0].(domain.Project)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockspecAssembler_Assemble_Call) Return(spec arch.Spec, err error) *mockspecAssembler_Assemble_Call {
	_c.Call.Return(spec, err)
	return _c
}

func (_c *mockspecAssembler_Assemble_Call) RunAndReturn(run func(prj domain.Project) (arch.Spec, error)) *mockspecAssembler_Assemble_Call {
	_c.Call.Return(run)
	return _c
}

// newMockreferenceRender creates a new instance of mockreferenceRender. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockreferenceRender(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockreferenceRender {
	mock := &mockreferenceRender{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockreferenceRender is an autogenerated mock type for the referenceRender type
type mockreferenceRender struct {
	mock.Mock
}

type mockreferenceRender_Expecter struct {
	mock *mock.Mock
}

func (_m *mockreferenceRender) EXPECT() *mockreferenceRender_Expecter {
	return &mockreferenceRender_Expecter{mock: &_m.Mock}
}

// SourceCode provides a mock function for the type mockreferenceRender
func (_mock *mockreferenceRender) SourceCode(ref domain.Reference, highlight bool, showPointer bool) []byte {
	ret := _mock.Called(ref, highlight, showPointer)

	if len(ret) == 0 {
		panic("no return value specified for SourceCode")
	}

	var r0 []byte
	if returnFunc, ok := ret.Get(0).(func(domain.Reference, bool, bool) []byte); ok {
		r0 = returnFunc(ref, highlight, showPointer)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	return r0
}

// mockreferenceRender_SourceCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SourceCode'
type mockreferenceRender_SourceCode_Call struct {
	*mock.Call
}

// SourceCode is a helper method to define mock.On call
//   - ref domain.Reference
//   - highlight bool
//   - showPointer bool
func (_e *mockreferenceRender_Expecter) SourceCode(ref any, highlight any, showPointer any) *mockreferenceRender_SourceCode_Call {
	return &mockreferenceRender_SourceCode_Call{Call: _e.mock.On("SourceCode", ref, highlight, showPointer)}
}

func (_c *mockreferenceRender_SourceCode_Call) Run(run func(ref domain.Reference, highlight bool, showPointer bool)) *mockreferenceRender_SourceCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 domain.Reference
		if args[0] != nil {
			arg0 = args[0].(domain.Reference)
		}
		var arg1 bool
		if args[1] != nil {
			arg1 = args[1].(bool)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockreferenceRender_SourceCode_Call) Return(bytes []byte) *mockreferenceRender_SourceCode_Call {
	_c.Call.Return(bytes)
	return _c
}

func (_c *mockreferenceRender_SourceCode_Call) RunAndReturn(run func(ref domain.Reference, highlight bool, showPointer bool) []byte) *mockreferenceRender_SourceCode_Call {
	_c.Call.Return(run)
	return _c
}

// newMockspecChecker creates a new instance of mockspecChecker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockspecChecker(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockspecChecker {
	mock := &mockspecChecker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockspecChecker is an autogenerated mock type for the specChecker type
type mockspecChecker struct {
	mock.Mock
}

type mockspecChecker_Expecter struct {
	mock *mock.Mock
}

func (_m *mockspecChecker) EXPECT() *mockspecChecker_Expecter {
	return &mockspecChecker_Expecter{mock: &_m.Mock}
}

// Check provides a mock function for the type mockspecChecker
func (_mock *mockspecChecker) Check(ctx context.Context, spec arch.Spec) (models.CheckResult, error) {
	ret := _mock.Called(ctx, spec)

	if len(ret) == 0 {
		panic("no return value specified for Check")
	}

	var r0 models.CheckResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, arch.Spec) (models.CheckResult, error)); ok {
		return returnFunc(ctx, spec)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, arch.Spec) models.CheckResult); ok {
		r0 = returnFunc(ctx, spec)
	} else {
		r0 = ret.Get(0).(models.CheckResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, arch.Spec) error); ok {
		r1 = returnFunc(ctx, spec)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockspecChecker_Check_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Check'
type mockspecChecker_Check_Call struct {
	*mock.Call
}

// Check is a helper method to define mock.On call
//   - ctx context.Context
//   - spec arch.Spec
func (_e *mockspecChecker_Expecter) Check(ctx any, spec any) *mockspecChecker_Check_Call {
	return &mockspecChecker_Check_Call{Call: _e.mock.On("Check", ctx, spec)}
}

func (_c *mockspecChecker_Check_Call) Run(run func(ctx context.Context, spec arch.Spec)) *mockspecChecker_Check_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 arch.Spec
		if args[1] != nil {
			arg1 = args[1].(arch.Spec)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockspecChecker_Check_Call) Return(checkResult models.CheckResult, err error) *mockspecChecker_Check_Call {
	_c.Call.Return(checkResult, err)
	return _c
}

func (_c *mockspecChecker_Check_Call) RunAndReturn(run func(ctx context.Context, spec arch.Spec) (models.CheckResult, error)) *mockspecChecker_Check_Call {
	_c.Call.Return(run)
	return _c
}
