// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package checker

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockSuppressIndex creates a new instance of MockSuppressIndex. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSuppressIndex(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSuppressIndex {
	mock := &MockSuppressIndex{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSuppressIndex is an autogenerated mock type for the SuppressIndex type
type MockSuppressIndex struct {
	mock.Mock
}

type MockSuppressIndex_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSuppressIndex) EXPECT() *MockSuppressIndex_Expecter {
	return &MockSuppressIndex_Expecter{mock: &_m.Mock}
}

// HasDirectives provides a mock function for the type MockSuppressIndex
func (_mock *MockSuppressIndex) HasDirectives() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for HasDirectives")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockSuppressIndex_HasDirectives_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasDirectives'
type MockSuppressIndex_HasDirectives_Call struct {
	*mock.Call
}

// HasDirectives is a helper method to define mock.On call
func (_e *MockSuppressIndex_Expecter) HasDirectives() *MockSuppressIndex_HasDirectives_Call {
	return &MockSuppressIndex_HasDirectives_Call{Call: _e.mock.On("HasDirectives")}
}

func (_c *MockSuppressIndex_HasDirectives_Call) Run(run func()) *MockSuppressIndex_HasDirectives_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSuppressIndex_HasDirectives_Call) Return(b bool) *MockSuppressIndex_HasDirectives_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockSuppressIndex_HasDirectives_Call) RunAndReturn(run func() bool) *MockSuppressIndex_HasDirectives_Call {
	_c.Call.Return(run)
	return _c
}

// IsFileSuppressed provides a mock function for the type MockSuppressIndex
func (_mock *MockSuppressIndex) IsFileSuppressed(path string) bool {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for IsFileSuppressed")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(string) bool); ok {
		r0 = returnFunc(path)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockSuppressIndex_IsFileSuppressed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsFileSuppressed'
type MockSuppressIndex_IsFileSuppressed_Call struct {
	*mock.Call
}

// IsFileSuppressed is a helper method to define mock.On call
//   - path string
func (_e *MockSuppressIndex_Expecter) IsFileSuppressed(path any) *MockSuppressIndex_IsFileSuppressed_Call {
	return &MockSuppressIndex_IsFileSuppressed_Call{Call: _e.mock.On("IsFileSuppressed", path)}
}

func (_c *MockSuppressIndex_IsFileSuppressed_Call) Run(run func(path string)) *MockSuppressIndex_IsFileSuppressed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSuppressIndex_IsFileSuppressed_Call) Return(b bool) *MockSuppressIndex_IsFileSuppressed_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockSuppressIndex_IsFileSuppressed_Call) RunAndReturn(run func(path string) bool) *MockSuppressIndex_IsFileSuppressed_Call {
	_c.Call.Return(run)
	return _c
}

// IsLineSuppressed provides a mock function for the type MockSuppressIndex
func (_mock *MockSuppressIndex) IsLineSuppressed(path string, line int, dependencyTarget string) bool {
	ret := _mock.Called(path, line, dependencyTarget)

	if len(ret) == 0 {
		panic("no return value specified for IsLineSuppressed")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(string, int, string) bool); ok {
		r0 = returnFunc(path, line, dependencyTarget)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockSuppressIndex_IsLineSuppressed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsLineSuppressed'
type MockSuppressIndex_IsLineSuppressed_Call struct {
	*mock.Call
}

// IsLineSuppressed is a helper method to define mock.On call
//   - path string
//   - line int
//   - dependencyTarget string
func (_e *MockSuppressIndex_Expecter) IsLineSuppressed(path any, line any, dependencyTarget any) *MockSuppressIndex_IsLineSuppressed_Call {
	return &MockSuppressIndex_IsLineSuppressed_Call{Call: _e.mock.On("IsLineSuppressed", path, line, dependencyTarget)}
}

func (_c *MockSuppressIndex_IsLineSuppressed_Call) Run(run func(path string, line int, dependencyTarget string)) *MockSuppressIndex_IsLineSuppressed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSuppressIndex_IsLineSuppressed_Call) Return(b bool) *MockSuppressIndex_IsLineSuppressed_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockSuppressIndex_IsLineSuppressed_Call) RunAndReturn(run func(path string, line int, dependencyTarget string) bool) *MockSuppressIndex_IsLineSuppressed_Call {
	_c.Call.Return(run)
	return _c
}
