// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package explain

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/vsfedorenko/go-arch-lint/v3/internal/models"
	"github.com/vsfedorenko/go-arch-lint/v3/internal/models/arch"
	"github.com/vsfedorenko/go-arch-lint/v3/internal/models/domain"
)

// newMockspecAssembler creates a new instance of mockspecAssembler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockspecAssembler(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockspecAssembler {
	mock := &mockspecAssembler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockspecAssembler is an autogenerated mock type for the specAssembler type
type mockspecAssembler struct {
	mock.Mock
}

type mockspecAssembler_Expecter struct {
	mock *mock.Mock
}

func (_m *mockspecAssembler) EXPECT() *mockspecAssembler_Expecter {
	return &mockspecAssembler_Expecter{mock: &_m.Mock}
}

// Assemble provides a mock function for the type mockspecAssembler
func (_mock *mockspecAssembler) Assemble(prj domain.Project) (arch.Spec, error) {
	ret := _mock.Called(prj)

	if len(ret) == 0 {
		panic("no return value specified for Assemble")
	}

	var r0 arch.Spec
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(domain.Project) (arch.Spec, error)); ok {
		return returnFunc(prj)
	}
	if returnFunc, ok := ret.Get(0).(func(domain.Project) arch.Spec); ok {
		r0 = returnFunc(prj)
	} else {
		r0 = ret.Get(0).(arch.Spec)
	}
	if returnFunc, ok := ret.Get(1).(func(domain.Project) error); ok {
		r1 = returnFunc(prj)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockspecAssembler_Assemble_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Assemble'
type mockspecAssembler_Assemble_Call struct {
	*mock.Call
}

// Assemble is a helper method to define mock.On call
//   - prj domain.Project
func (_e *mockspecAssembler_Expecter) Assemble(prj any) *mockspecAssembler_Assemble_Call {
	return &mockspecAssembler_Assemble_Call{Call: _e.mock.On("Assemble", prj)}
}

func (_c *mockspecAssembler_Assemble_Call) Run(run func(prj domain.Project)) *mockspecAssembler_Assemble_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 domain.Project
		if args[0] != nil {
			arg0 = args[0].(domain.Project)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockspecAssembler_Assemble_Call) Return(spec arch.Spec, err error) *mockspecAssembler_Assemble_Call {
	_c.Call.Return(spec, err)
	return _c
}

func (_c *mockspecAssembler_Assemble_Call) RunAndReturn(run func(prj domain.Project) (arch.Spec, error)) *mockspecAssembler_Assemble_Call {
	_c.Call.Return(run)
	return _c
}

// newMockprojectInfoAssembler creates a new instance of mockprojectInfoAssembler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockprojectInfoAssembler(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockprojectInfoAssembler {
	mock := &mockprojectInfoAssembler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockprojectInfoAssembler is an autogenerated mock type for the projectInfoAssembler type
type mockprojectInfoAssembler struct {
	mock.Mock
}

type mockprojectInfoAssembler_Expecter struct {
	mock *mock.Mock
}

func (_m *mockprojectInfoAssembler) EXPECT() *mockprojectInfoAssembler_Expecter {
	return &mockprojectInfoAssembler_Expecter{mock: &_m.Mock}
}

// ProjectInfo provides a mock function for the type mockprojectInfoAssembler
func (_mock *mockprojectInfoAssembler) ProjectInfo(rootDirectory string, archFilePath string) (domain.Project, error) {
	ret := _mock.Called(rootDirectory, archFilePath)

	if len(ret) == 0 {
		panic("no return value specified for ProjectInfo")
	}

	var r0 domain.Project
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) (domain.Project, error)); ok {
		return returnFunc(rootDirectory, archFilePath)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) domain.Project); ok {
		r0 = returnFunc(rootDirectory, archFilePath)
	} else {
		r0 = ret.Get(0).(domain.Project)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(rootDirectory, archFilePath)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockprojectInfoAssembler_ProjectInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProjectInfo'
type mockprojectInfoAssembler_ProjectInfo_Call struct {
	*mock.Call
}

// ProjectInfo is a helper method to define mock.On call
//   - rootDirectory string
//   - archFilePath string
func (_e *mockprojectInfoAssembler_Expecter) ProjectInfo(rootDirectory any, archFilePath any) *mockprojectInfoAssembler_ProjectInfo_Call {
	return &mockprojectInfoAssembler_ProjectInfo_Call{Call: _e.mock.On("ProjectInfo", rootDirectory, archFilePath)}
}

func (_c *mockprojectInfoAssembler_ProjectInfo_Call) Run(run func(rootDirectory string, archFilePath string)) *mockprojectInfoAssembler_ProjectInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockprojectInfoAssembler_ProjectInfo_Call) Return(project domain.Project, err error) *mockprojectInfoAssembler_ProjectInfo_Call {
	_c.Call.Return(project, err)
	return _c
}

func (_c *mockprojectInfoAssembler_ProjectInfo_Call) RunAndReturn(run func(rootDirectory string, archFilePath string) (domain.Project, error)) *mockprojectInfoAssembler_ProjectInfo_Call {
	_c.Call.Return(run)
	return _c
}

// newMockprojectFilesResolver creates a new instance of mockprojectFilesResolver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockprojectFilesResolver(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockprojectFilesResolver {
	mock := &mockprojectFilesResolver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockprojectFilesResolver is an autogenerated mock type for the projectFilesResolver type
type mockprojectFilesResolver struct {
	mock.Mock
}

type mockprojectFilesResolver_Expecter struct {
	mock *mock.Mock
}

func (_m *mockprojectFilesResolver) EXPECT() *mockprojectFilesResolver_Expecter {
	return &mockprojectFilesResolver_Expecter{mock: &_m.Mock}
}

// ProjectFiles provides a mock function for the type mockprojectFilesResolver
func (_mock *mockprojectFilesResolver) ProjectFiles(ctx context.Context, spec arch.Spec) ([]models.FileHold, error) {
	ret := _mock.Called(ctx, spec)

	if len(ret) == 0 {
		panic("no return value specified for ProjectFiles")
	}

	var r0 []models.FileHold
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, arch.Spec) ([]models.FileHold, error)); ok {
		return returnFunc(ctx, spec)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, arch.Spec) []models.FileHold); ok {
		r0 = returnFunc(ctx, spec)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.FileHold)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, arch.Spec) error); ok {
		r1 = returnFunc(ctx, spec)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockprojectFilesResolver_ProjectFiles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProjectFiles'
type mockprojectFilesResolver_ProjectFiles_Call struct {
	*mock.Call
}

// ProjectFiles is a helper method to define mock.On call
//   - ctx context.Context
//   - spec arch.Spec
func (_e *mockprojectFilesResolver_Expecter) ProjectFiles(ctx any, spec any) *mockprojectFilesResolver_ProjectFiles_Call {
	return &mockprojectFilesResolver_ProjectFiles_Call{Call: _e.mock.On("ProjectFiles", ctx, spec)}
}

func (_c *mockprojectFilesResolver_ProjectFiles_Call) Run(run func(ctx context.Context, spec arch.Spec)) *mockprojectFilesResolver_ProjectFiles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 arch.Spec
		if args[1] != nil {
			arg1 = args[1].(arch.Spec)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockprojectFilesResolver_ProjectFiles_Call) Return(fileHolds []models.FileHold, err error) *mockprojectFilesResolver_ProjectFiles_Call {
	_c.Call.Return(fileHolds, err)
	return _c
}

func (_c *mockprojectFilesResolver_ProjectFiles_Call) RunAndReturn(run func(ctx context.Context, spec arch.Spec) ([]models.FileHold, error)) *mockprojectFilesResolver_ProjectFiles_Call {
	_c.Call.Return(run)
	return _c
}
